WALL_RANGE_SPREAD = 0.00028  # Maksimalni raspon za zidove
PRICE_PRECISION = 5  # Cene na 5 decimala
VOLUME_PRECISION = 2  # Volumen na 2 decimale
MIN_WALL_VOLUME = 50.0  # Minimalni volumen za zid (ETH)
HILL_WALL_VOLUME = 150.0  # "Brdašce"
MOUNTAIN_WALL_VOLUME = 250.0  # "Brdo"
EPIC_WALL_VOLUME = 500.0  # "Planina"
TARGET_DIGITS = [2, 3, 7, 8]  # Prioritet za 5. decimalu
SPECIAL_DIGITS = [1, 9]  # Za obrnute poteze (rokada)
PROFIT_TARGET = 0.00004  # Cilj: 4 pipsa
LEVERAGE = 5  # Leverage x20