version: '3.8'
services:
  bot:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./data.json:/app/data.json
      - ./html:/app/html:ro

    working_dir: /app
    ports:
      - "8888:80"
      - "8000:8000"
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge