services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./logs:/app/logs
      - ./data.json:/app/data.json
      - ./html:/app/html:ro
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - bot_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    volumes:
      - ./logs:/app/logs
      - ./data.json:/app/data.json
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - bot_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
      - ./logs:/var/log/nginx
      - /dev/null:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - main
      - api
    restart: unless-stopped
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge