services:
  main:
    build:
      context: .
      dockerfile: Dockerfile.main
    environment:
      - GROK_API_KEY=${GROK_API_KEY}
    secrets:
      - grok_api_key
    networks:
      - default
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    networks:
      - default
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - main
      - api
    networks:
      - default
    restart: unless-stopped

secrets:
  grok_api_key:
    file: ./.env

networks:
  default:
    driver: bridge