version: '3.8'
services:
  bot:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "80:80"
      - "8000:8000"
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge